### ISSUE TITLE
{'Informacja': 'Niepoprawny hash przesyłanej wiadomości.', 'Kod': 403}

### ISSUE THREAD

**Issue by pad19pl** [pnowosie/ifirma-api#11]
Hi,
I am keep getting error:
{'Informacja': 'Niepoprawny hash przesyłanej wiadomości.', 'Kod': 403}
18.06.2022

is anything need to be change in code, maybe there was some update of ifirma?
I've tried on two ifirma accounts and getting the same error.
In config.py I am adding 
`    api_user or os.environ.get("IFIRMA_API_USERNAME", "mymail@o2.pl"),    
    api_key or os.environ.get("IFIRMA_API_KEY", b'9C5A5F59DBA4141F')`

**Comment by pnowosie** [comment]
I believe you were able to solve it already or you've given up on this project ;)

Environment variable's value is a string so the default value shall also be a string. I've added binary as an option but it isn't really used anywhere - but only makes confusion.

Also please note that usage of env variables are there to protect secrets from being revealed in plaintext.
Simplest way to play with the lib is to review scripts in [sample_invoice folder](https://github.com/pnowosie/ifirma-api/tree/main/sample_invoice).
To run them I do the following:
```
# start terminal from repo root
export IFIRMA_API_USERNAME=...
export IFIRMA_API_KEY=...
.venv/bin/python sample_invoice/list_invoices.py
```
