### ISSUE TITLE
Wersja na pypi

### ISSUE THREAD

**Issue by OceanFireSoftware** [pnowosie/ifirma-api#2]
Nie działa instalacja poprzez pypi

Komenda:
`pip install pnowosie.ifirma-api`

Rezultatem byłoby zainstalowanie zależności. Niestety wyskakuje błąd, że nie znaleziono pakietu.

**Comment by pnowosie** [comment]
Hmm, czy to nie jest problem z twoim setupem / czy coś chwilowego po stronie pypi.org?
Sprawdziłem przed chwilą lokalnie

<img width="551" alt="obraz" src="https://user-images.githubusercontent.com/1813036/117064198-2cfbe400-ad26-11eb-9deb-52b755fd0115.png">

**Comment by OceanFireSoftware** [comment]
Dla komendy

`
pip install -e git+git@github.com:pnowosie/ifirma-api.git#egg=pnowosie.ifirma-api
`

Błąd:

`
ERROR: git+git@github.com:pnowosie/ifirma-api.git#egg=pnowosie.ifirma-api is not a valid editable requirement. It should either be a path to a local project or a VCS URL (beginning with bzr+http, bzr+https, bzr+ssh, bzr+sftp, bzr+ftp, bzr+lp, bzr+file, git+http, git+https, git+ssh, git+git, git+file, hg+file, hg+http, hg+https, hg+ssh, hg+static-http, svn+ssh, svn+http, svn+https, svn+svn, svn+file).
`

Dla komendy:

`
pip install pnowosie.ifirma-api
`

Błąd:

`
ERROR: Could not find a version that satisfies the requirement pnowosie.ifirma-api (from versions: none)
ERROR: No matching distribution found for pnowosie.ifirma-api
`
