### ISSUE TITLE
Error: "Data wystawienia faktury nie może być późniejsza niż 15 dzień miesiąca następnego względem miesiąca sprzedaży"

### ISSUE THREAD

**Issue by OceanFireSoftware** [pnowosie/ifirma-api#3]
When I try to send invoice, I get an error:
`
<ifirma.request.InvoiceResponse object at 0x7fea077a73d0> Data wystawienia faktury nie może być późniejsza niż 15 dzień miesiąca następnego względem miesiąca sprzedaży
`

Code:
`        from ifirma.invoice import (Invoice, Customer, InvoicePosition, INVOICE_TYPE)
        from ifirma.request import send_invoice, send_email

        invoice = Invoice(
            invoice_type=INVOICE_TYPE.NON_VAT_PAYER
        ).with_issuer(
            'Krystian Magdziarz'
        ).with_payed(
            float(38.82)
        ).with_comments(
            f"Nr zamówienia: {1}"
        ).with_position(
            InvoicePosition("Super pozycja", float(38.82))
        ).with_new_customer(
            Customer("Krystian MAGDZIARZ", "krystianmagdziarz@gmail.com", "05-850", "Ożarów Mazowiecki", "Poznańska 270", None)
        )

        create_invoice_response = send_invoice(invoice)
        print(create_invoice_response, create_invoice_response.message)`

**Comment by OceanFireSoftware** [comment]
Problem solved. The message appears when we do not change the accounting month in the dashboard.

**Comment by pnowosie** [comment]
Taking into account the frequency of tax regulation changes I don't even try to handle errors passing the error messages untouched. Kudos to ifirma's team which keeps align their api with this crazy 💩
